apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiworld
  labels:
    app: hiworld
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hiworld
  template:
    metadata:
      labels:
        app: hiworld
    spec:
      containers:
      - name: hiworld
        image: "kehaokh/hiworld:{{ .Chart.AppVersion }}"
        ports:
        - containerPort: 8080
